#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  amixer -D pulse  sset Master 5%+
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  amixer -D pulse sset Master toggle 
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  amixer -D pulse sset Master 5%- 
fi

#statusLine=$(amixer get Master | tail -n 1)
#status=$(echo "${statusLine}" | grep -wo "on")
volume=$(amixer -D pulse get Master | awk '{ print $5 }'| tr -d '[]%' | tail -n 1)

if [[ $(amixer get Master | awk '{print $6 }' | tr -d '[]%' | tail -n 1) == "off" ]]; then
	echo "Mute"
else
	echo "${volume}%"
fi
